@echo off
echo Activando entorno virtual...
call venv\Scripts\activate
echo Instalando dependencias (si es necesario)...
pip install -r requirements.txt
echo Ejecutando aplicativo...
streamlit run app_estatica.py
